---
platforms:
  - name: debian-10
    groups:
      - nomad_instances
    image: dokken/debian-10
    command: /lib/systemd/systemd
    dockerfile: ../_shared/Dockerfile.j2
    cgroupns: host
    privileged: true
